<table id="m1mainSXMenu1" cellspacing="0" cellpadding="0" border="0" bgcolor="#FFFFFF" width="100%"><tr><td><table id="m1mainSXMenu2" cellspacing="1" cellpadding="4" class="x1" border="0" width="100%" width="100%">
<tr align="center">
<td onmouseover="chgBg(m1,'m1tlm0',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm0',0,1)"  id="m1tlm0"  class="m1mit" 
 bgcolor="#3e7719">

<a id="m1tlm0a" class="m1CL0" href="/" ><div class='topFold'>Home<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm1',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm1',0,1)" id="m1tlm1" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm1a" class="m1CL0" href="/team.shtml" ><div class='topFold'>Our Team<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm2',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm2',0,1)" id="m1tlm2" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm2a" class="m1CL0" href="/online_bidding_information.shtml" ><div class='topFold'>How to Bid<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm3',3);exM(m1,'m1mn1','m1tlm3',event)"
onmouseout="chgBg(m1,'m1tlm3',0);coM(m1,'m1mn1')" id="m1tlm3" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm3a" class="m1CL0" href="/auctionqa.shtml"  onMouseOver="exMNS(m1,'m1mn1',event)"
onmouseout="coMNS(m1,'m1mn1')" >
<div id='m1mn1top' class='topFold'>Auction Q & A<img id="hidim1" class="hidim" width="8" height="8" src="/scripts/sitemap_m1ia.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td bgcolor="#3e7719" >
<a id="m1tlm4a" class="m1CL0" href="/consignment_info.shtml" ><div class='topFold'>How to Consign<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td bgcolor="#3e7719" >
<a id="m1tlm4a" class="m1CL0" href="/estates.shtml" ><div class='topFold'>Estate Sales<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td bgcolor="#3e7719" >
<a id="m1tlm4a" class="m1CL0" href="/cgi-bin/mncal.cgi?auctionmnr" ><div class='topFold'>Real Estate Listings<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td onmouseover="chgBg(m1,'m1tlm5',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm5',0,1)" id="m1tlm5" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm5a" class="m1CL0" href="/whyaaa.shtml" ><div class='topFold'>Why Choose Us?<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td onmouseover="chgBg(m1,'m1tlm6',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm6',0,1)" id="m1tlm6" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm6a" class="m1CL0" href="/benefittest.shtml" ><div class='topFold'>Testimonials<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td onmouseover="chgBg(m1,'m1tlm6',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm6',0,1)" id="m1tlm6" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm6a" class="m1CL0" href="https://server2.maxanet.com/cgi-bin/mnregister.cgi?auctionmn" ><div class='topFold'>Register to Bid<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>


<tr align="center"><td onmouseover="chgBg(m1,'m1tlm7',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm7',0,1)" id="m1tlm7" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm7a" class="m1CL0" href="/cgi-bin/mdemail.cgi?auctionmn" ><div class='topFold'>E-Mail Registration<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm8',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm8',0,1)" id="m1tlm8" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm8a" class="m1CL0" href="/video1.shtml" ><div class='topFold'>Benefit Auctions<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm9',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm9',0,1)" id="m1tlm9" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm9a" class="m1CL0" href="/tonysblog.shtml" ><div class='topFold'>Tony's Auction Blog<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>

<tr align="center"><td onmouseover="chgBg(m1,'m1tlm10',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm10',0,1)" id="m1tlm10" class="m1mit" 
bgcolor="#3e7719" >
<a id="m1tlm10a" class="m1CL0" href="/contact.shtml" ><div class='topFold'>Contact Us<img width="8" height="8" src="/scripts/empty.gif" align="texttop" border="0" /></div></a></td></tr>
</table></td></tr>
</table>
