<table id="m1mainSXMenu1" cellspacing="0" cellpadding="0" border="0" bgcolor="#FFFFFF" width="100%"><tr><td><table id="m1mainSXMenu2" cellspacing="1" cellpadding="4" class="x1" border="0" width="100%" width="100%">
<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm0',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm0',0,1)"  id="m1tlm0"  class="m1mit" bgcolor="#3e7719">
			<a id="m1tlm0a" class="m1CL0" href="/" >
				<div class='topFold'>Home<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm1',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm1',0,1)" id="m1tlm1" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm1a" class="m1CL0" href="/team.shtml" >
				<div class='topFold'>Our Team<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm2',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm2',0,1)" id="m1tlm2" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm2a" class="m1CL0" href="/online_bidding_information.shtml" >
				<div class='topFold'>How to Bid<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm3',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm3',0,1)" id="m1tlm3" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm3a" class="m1CL0" href="/auctionqa.shtml" >
				<div class='topFold'>Auction Q & A<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm4',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm4',0,1)" id="m1tlm4" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm4a" class="m1CL0" href="/benefitqa.shtml" >
				<div class='topFold'>Benefit Q & A<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm5',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm5',0,1)" id="m1tlm5" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm5a" class="m1CL0" href="/reqa.shtml" >
				<div class='topFold'>Real Estate Q & A<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm7',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm7',0,1)" id="m1tlm7" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm7a" class="m1CL0" href="/selling-methods.shtml" >
				<div class='topFold'>Selling Methods and Fees<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm6',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm6',0,1)" id="m1tlm6" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm6a" class="m1CL0" href="/consignment_info.shtml" >
				<div class='topFold'>Selling Tips<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm13',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm13',0,1)" id="m1tlm13" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm13a" class="m1CL0" href="/items-that-sell.shtml" >
				<div class='topFold'>Items That Sell<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm8',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm8',0,1)" id="m1tlm8" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm8a" class="m1CL0" href="/whyaaa.shtml" >
				<div class='topFold'>Why Choose Us?<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm16',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm16',0,1)" id="m1tlm16" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm16a" class="m1CL0" href="/how-to-choose-estate-selling-company.shtml" >
				<div class='topFold'>How To Choose A Company To Sell Your Estate<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>


	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm9',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm9',0,1)" id="m1tlm9" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm9a" class="m1CL0" href="/testimonials.shtml" >
				<div class='topFold'>Testimonials<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>


	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm10',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm10',0,1)" id="m1tlm10" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm10a" class="m1CL0" href="https://server2.maxanet.com/cgi-bin/mnregister.cgi?auctionmn" >
				<div class='topFold'>Register to Bid<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm11',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm11',0,1)" id="m1tlm11" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm11a" class="m1CL0" href="/general-terms-and-conditions.shtml" >
				<div class='topFold'>General Terms<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm12',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm12',0,1)" id="m1tlm12" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm12a" class="m1CL0" href="/cgi-bin/mdemail.cgi?auctionmn" >
				<div class='topFold'>E-Mail Registration<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm14',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm14',0,1)" id="m1tlm14" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm14a" class="m1CL0" href="/tonysblog.shtml" >
				<div class='topFold'>Tony's Auction Blog<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>

	<tr align="center">
		<td onmouseover="chgBg(m1,'m1tlm15',3);exM(m1,'none','',event)" onmouseout="chgBg(m1,'m1tlm15',0,1)" id="m1tlm15" class="m1mit" bgcolor="#3e7719" >
			<a id="m1tlm15a" class="m1CL0" href="/contact.shtml" >
				<div class='topFold'>Contact Us<img width="8" height="8" src="https://www.auctionmn.com/scripts/empty.gif" align="texttop" border="0" /></div>
			</a>
		</td>
	</tr>
</table></td></tr>
</table>
