//script generated by SiteXpert (www.xtreeme.com/sitexpert/)
//Copyright(C) 1998-2003 Xtreeme GmbH
NS60=(navigator.userAgent.indexOf("Netscape6/6.0")!=-1)
Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
IE4=(document.all&&!Opera)
mac=((IE4)&&(navigator.appVersion.indexOf("Mac")!=-1))
DOM=document.documentElement&&!IE4&&!Opera
NS4=navigator.appName.indexOf("Netscape")>-1&&!DOM
mswnd=(navigator.appVersion.indexOf("Windows")!=-1||navigator.appVersion.indexOf("WinNT")!=-1)
if(IE4){
av=navigator.appVersion
avi=av.indexOf("MSIE")
if(avi==-1){version=parseInt(av);}else{version=parseInt(av.substr(avi+4));}}
var ver='6.1.4EnStd'
var m1=new Object
m1.name='m1'
m1.fnm='sitemap_m1'
if(!window.lastm||window.lastm<1)lastm=1
if(NS4||IE4||DOM||Opera){
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.scrollDelay=50
m1.scrollStep=10
m1.showDelayedTimeout=null
m1.fadingSteps=8
m1.v21="/scripts"
m1.maxlev=1
m1.v22=0
m1.bVarWidth=0
m1.bShowDel=300
m1.v23=180
m1.levelOffset=20
m1.bord=1
m1.vertSpace=4
m1.sep=1
m1.v19=false
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame="content"
m1.menuFrame="tree"
m1.v24="content"
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg="#3e7719"
m1.tlmOrigCol="#d8d08d"
m1.v25=false
m1.popupOpacity=0
m1.v11=false
m1.rm=0
m1.v10=0
m1.popupLeftPad=5
m1.v01=2
m1.tlmHlBg="#4c4818"
m1.tlmHlCol="White"
m1.borderCol="#FFFFFF"
m1.menuHorizontal=false
m1.scrollHeight=6}
m1.lev0=new Array("10px",false,false,"#d8d08d","#3e7719","White","Arial,Verdana,Tahoma","#4c4818")
m1.lev1=new Array("10px",false,false,"#d8d08d","#3e7719","White","Arial,Verdana,Tahoma","#4c4818")
m1mn1=new Array
(
"Auction Q & A","/auctionqa.shtml",0
,"Real Estate<br>Auction Q & A","/reqa.shtml",0
,"Benefit<br>Auction Q & A","/benefitqa.shtml",0
,"Why Auctions Work","/whyauction.shtml",0
)
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.popupOffset=0
m1.v02=m1.v23
if(Opera&&!Opera7)document.write("<"+"script language='JavaScript1.2' src='/scripts/menu_opera.js'><"+"/"+"script>")
else if(NS4)document.write("<"+"script language='JavaScript1.2' src='/scripts/menu_ns4.js'><"+"/"+"script>")
else if(document.getElementById)document.write("<"+"script language='JavaScript1.2' src='/scripts/menu_dom.js'><"+"/"+"script>")
else document.write("<"+"script language='JavaScript1.2' src='/scripts/menu_ie4.js'><"+"/"+"script>")
document.write("<style type='text/css'>\n")
if(Opera7||IE4||DOM)document.write(".hidim{visibility:hidden}\n")
document.write(".m1CL0,.m1CL0:link{text-decoration:none;color:#d8d08d; }\n")
document.write(".m1CL0:visited{color:#d8d08d}\n")
document.write(".topFold{position:"+(!DOM&&!IE4?"relative":"static")+"}\n")
if(NS4&&!m1.v25)document.write(".x1{padding-left:10px;padding-right:10px;}\n")
document.write(".m1mit{"+((!NS4||m1.v25)?"padding-left:10px;padding-right:10px;":"")+"color:#d8d08d; font-family:Arial,Verdana,Tahoma; font-size:10px; }\n")
document.write("</style>\n\n")
